version: "3"

services:
  app-user-gtw:
      command: reflex -sr '\.go$|\.mod$' -- sh -c "go run cmd/main.go"
      build:
        dockerfile: Dockerfile.local
        context: .
      environment:
        - SERVICE_NAME=user-gtw
        - ENVRIONMENT=local
        - HTTP_SERVER_PORT=3000
        - USER_STORE_SVC_ADDR=http://172.20.0.5:50051
      volumes:
        - .:/go/src/app
      working_dir: /go/src/app
      ports:
        - "3000:3000"